// ページ内の固定UI文言（見出し・ラベル・ボタン等）。コンテンツ辞書に属さない文字列をここに集約（§10 / §16-2）。
import type { Lang } from '../i18n/config';

export const ui = {
  ja: {
    common: {
      skipToContent: '本文へスキップ',
      breadcrumbHome: 'ホーム',
      langLabel: '言語',
    },
    plan: {
      recommendedBadge: '推奨プラン',
      monthly: '月額',
      perMonth: '/月',
      setup: (v: string) => `初期構築 ${v}（一回）`,
      cta: 'このプランで相談する',
    },
    footer: {
      sitemap: 'SITEMAP',
      contact: 'CONTACT',
      follow: 'FOLLOW',
      freeConsult: '無料相談',
      areasPrefix: '対応エリア：',
      privacy: 'プライバシーポリシー',
    },
    form: {
      name: 'お名前',
      shop: '店舗名',
      email: 'メールアドレス',
      required: '必須',
      location: '所在地（任意）',
      locationSelect: '選択してください',
      locGc: 'ゴールドコースト市内',
      locBrisbane: 'ゴールドコースト近郊',
      locOther: 'その他',
      planInterest: 'ご興味のあるプラン（任意）',
      planUndecided: '未定・相談して決めたい',
      planUme: '梅・立ち上げ',
      planTake: '竹・集客',
      planMatsu: '松・ブランド成長',
      sns: '店舗のInstagram / WebサイトURL（任意）',
      message: 'ご相談内容（任意）',
      messagePlaceholder: '現状のお悩みやご希望があればお書きください。空欄のままでも大丈夫です。',
      error: '送信に失敗しました。お手数ですが時間をおいて再度お試しいただくか、メールで直接ご連絡ください。',
      submit: '無料相談を申し込む',
      submitting: '送信中…',
      privacyNote1: '送信いただいた内容は',
      privacyNoteLink: 'プライバシーポリシー',
      privacyNote2: 'に基づき取り扱います。通常1〜2営業日以内にご返信します。',
      honeypotLabel: 'このフィールドは空のままにしてください',
    },
    cookie: {
      text1: '当サイトでは、サイト改善のためにCookieを使用したアクセス解析を行っています。詳しくは',
      link: 'プライバシーポリシー',
      text2: 'をご覧ください。',
      decline: '同意しない',
      accept: '同意する',
    },
    figures: {
      discovery: {
        step1Title: '① 探す・認知',
        step1Sub: '入口は分散している',
        step2Title: '② 確かめる・信頼',
        step2Sub: 'すべてが1点に集まる',
        hubName: 'Instagram',
        hubDesc1: '施術・雰囲気・人柄を確認する',
        hubDesc2: '“信頼のハブ”',
        hubNote: 'Google・Freshaのレビューで1次選別 → Instagramで最終確認',
        step3Title: '③ 予約',
        step3Sub: '「ここに行きたい」が決まる',
        entries: ['Googleマップ・検索', 'Fresha（予約マーケット）', 'Instagram（発見）', '口コミ・紹介', '在豪日本人メディア'],
        bookings: ['Instagram DM', 'Fresha 予約リンク'],
        caption: 'オーストラリアにはホットペッパーのような一強プラットフォームがなく、分散した入口が Instagram という1点に集まって予約が決まります。',
        aria: 'オーストラリアでのお店の探され方の図解。Googleマップ・Fresha・Instagram・口コミ・在豪日本人メディアという分散した入口が、信頼のハブであるInstagramに集まり、Instagram DMまたはFreshaでの予約につながる。',
      },
      loop: {
        nodes: [
          { label: '認知', sub: 'Instagram・MEO・レビュー' },
          { label: '検討・予約', sub: 'Web・予約導線' },
          { label: 'リピート・再来', sub: 'SMS・メール・Fresha' },
          { label: '紹介・レビュー', sub: 'レビュー獲得・UGC' },
        ],
        centerTitle: '来店・施術',
        centerSub: 'オーナー様の領分',
        reflow: 'レビューが認知へ還流 ↻',
        legendOurs: '私たちが運用する領域',
        legendClient: 'オーナー様の領分（接客・技術）',
        caption: '輪の軸はレビュー。良い施術 → レビュー → 検索上位＆社会的証明 → 新規来店、の循環をつくります。',
        title: '集客の輪（図解）',
        desc: '認知、検討・予約、来店・施術、リピート・再来、紹介・レビューが輪になって循環する図。中央の来店・施術だけがオーナーの領分で、それ以外の輪はすべて私たちが運用する。レビューが認知へ還流して輪が回り続ける。',
      },
    },
    home: {
      pricingLabel: 'Pricing',
      pricingHeading: '明朗な料金で、安心してご検討いただけます。',
      pricingLead: 'すべて〈初期構築（一回）＋ 月額（継続）＋ オプション（都度）〉の三層です。',
      pricingMore: 'オプション・料金の詳細を見る →',
      worksLabel: 'Works',
      worksHeading: '実績・事例',
      worksLead: 'ゴールドコーストの美容サロン様と取り組んできた事例をご紹介します。',
      worksMore: '実績一覧を見る',
      faqLabel: 'FAQ',
      faqHeading: 'よくある質問',
      faqMore: 'すべての質問を見る →',
      serviceMore: 'サービス詳細を見る →',
      aboutMore: '私たちについて詳しく →',
      logoLabel: (i: number) => `実績・媒体ロゴ ${i}`,
      heroImageLabel: 'ヒーロー主画像（サロン / ライフスタイル / ゴールドコースト）',
      avatarLabel: '顔写真',
      thumbLabel: (name: string) => `${name} サムネイル`,
      portraitLabel: (role: string) => `${role} ポートレート`,
    },
    service: {
      heading: '点（投稿）ではなく、輪（仕組み）を回す。',
      lead: '単発のSNS代行やWeb制作ではありません。サロンの集客の輪全体を、外部パートナーとして継続的に回し続けるサービスです。',
      scopeLabel: 'Scope',
      scopeHeading: '輪のどの段階で、何をするか。',
      scopeLead: '段階ごとに担当範囲と主な施策をはっきりさせています。',
      navLabel: 'サービス',
    },
    pricing: {
      heading: '料金の考え方は、シンプルな三層です。',
      lead: '〈初期構築（一回）＋ 月額（継続）＋ オプション(都度)〉。最初に土台を作り、毎月の運用で輪を回し、必要なときだけオプションを足す——分かりやすさを大切にしています。',
      optionsLabel: 'Options',
      optionsHeading: 'オプション（共通・都度）',
      optionsLead: 'どのプランにも追加できます。',
      tableOption: 'オプション',
      tablePrice: '料金',
      tableNote: '備考',
      faqLabel: 'FAQ',
      faqHeading: '料金についてよくある質問',
      bandHeading: 'どのプランが合うか、一緒に考えます。',
      bandSub: '現状をお聞きして、最適なプランを率直にご提案します。梅で十分な場合は、そうお伝えします。',
      navLabel: '料金',
    },
    works: {
      heading: '実績・事例',
      lead: '課題 → 施策 → 結果の流れで、実際の取り組みをご紹介します。',
      navLabel: '実績・事例',
      challenge: '課題',
      approach: '施策',
      result: '結果',
      deliverables: '制作物',
      mainVisual: (name: string) => `${name} メインビジュアル`,
      detailBandHeading: 'あなたのサロンでも、同じ仕組みを。',
    },
    about: {
      heading: '日本の品質を、現地の信頼で届ける。',
      lead: '私たちは、日本とオーストラリア・ゴールドコーストにまたがる2人組のチームです。',
      story: [
        '日本側は、Web制作・Instagram運用・集客の仕組み化・分析改善を担当。日本で磨いてきたマーケティングと制作のノウハウを、そのままゴールドコーストの美容サロン様にお届けします。',
        'オーストラリア側は、ゴールドコースト在住7年。営業・現地での折衝・撮影の連携・そして何より、オーナー様との信頼関係づくりと顧客成功を担当します。',
        '技術力の高い日本人オーナーの美容サロンが、デジタル集客の壁——英語、現地市場の理解、誰に任せればいいのか分からない不安——でつまずいているのを、私たちは現地でたくさん見てきました。',
        'だから私たちは、「日本品質の実行力 × 現地の信頼」という形でこの事業を始めました。単発の制作や投稿代行ではなく、集客の輪全体を回し続ける“成長パートナー”として、サロンの隣に立ち続けます。',
      ],
      teamHeading: 'チーム',
      valuesLabel: 'Values',
      valuesHeading: '私たちが大切にしていること',
      areasPrefix: '対応エリア：',
      navLabel: '私たちについて',
    },
    faq: {
      heading: 'よくある質問',
      lead: 'ここにない疑問は、無料相談で何でもお聞きください。',
      navLabel: 'よくある質問',
    },
    contact: {
      heading: 'まずは30分、無料でお話ししませんか。',
      lead: '現状のヒアリングと、できることのご提案だけでも大丈夫です。フォーム送信後、1〜2営業日以内にご返信します。',
      bookingHeading: '日程をその場で押さえたい方へ',
      bookingBody: 'カレンダーから直接、無料相談の日時をご予約いただけます。',
      bookingButton: '予約カレンダーを開く',
      bookingPlaceholder: '予約ツール埋め込み予定（Calendly / TimeRex / Spir）',
      otherHeading: 'その他の連絡方法',
      emailPrefix: 'メール：',
      areasPrefix: '対応エリア：',
      navLabel: '無料相談',
    },
    thanks: {
      heading: '送信ありがとうございます。',
      body1: '内容を確認のうえ、',
      bodyStrong: '1〜2営業日以内',
      body2: 'にメールでご返信いたします。',
      body3: '確認の自動返信メールが届かない場合は、迷惑メールフォルダをご確認いただくか、',
      body4: 'まで直接ご連絡ください。',
      back: 'トップページへ戻る',
    },
    privacy: {
      title: 'プライバシーポリシー',
      updated: '最終更新日：2026年6月13日',
    },
  },

  en: {
    common: {
      skipToContent: 'Skip to content',
      breadcrumbHome: 'Home',
      langLabel: 'Language',
    },
    plan: {
      recommendedBadge: 'Recommended',
      monthly: 'Monthly',
      perMonth: '/mo',
      setup: (v: string) => `Setup ${v} (one-off)`,
      cta: 'Enquire about this plan',
    },
    footer: {
      sitemap: 'SITEMAP',
      contact: 'CONTACT',
      follow: 'FOLLOW',
      freeConsult: 'Free consult',
      areasPrefix: 'Areas served: ',
      privacy: 'Privacy Policy',
    },
    form: {
      name: 'Name',
      shop: 'Salon name',
      email: 'Email address',
      required: 'required',
      location: 'Location (optional)',
      locationSelect: 'Please select',
      locGc: 'Gold Coast (city)',
      locBrisbane: 'Gold Coast surrounds',
      locOther: 'Other',
      planInterest: 'Plan you’re interested in (optional)',
      planUndecided: 'Not sure — let’s decide together',
      planUme: 'Starter',
      planTake: 'Growth',
      planMatsu: 'Brand',
      sns: 'Your salon’s Instagram / website URL (optional)',
      message: 'Your enquiry (optional)',
      messagePlaceholder: 'Tell us about your current challenges or goals. It’s fine to leave this blank.',
      error: 'Something went wrong. Please try again shortly, or email us directly.',
      submit: 'Request a free consult',
      submitting: 'Sending…',
      privacyNote1: 'Your details are handled in line with our ',
      privacyNoteLink: 'Privacy Policy',
      privacyNote2: '. We usually reply within 1–2 business days.',
      honeypotLabel: 'Please leave this field empty',
    },
    cookie: {
      text1: 'We use cookies for analytics to improve this site. For details, see our ',
      link: 'Privacy Policy',
      text2: '.',
      decline: 'Decline',
      accept: 'Accept',
    },
    figures: {
      discovery: {
        step1Title: '① Discover',
        step1Sub: 'Entry points are scattered',
        step2Title: '② Build trust',
        step2Sub: 'Everything converges here',
        hubName: 'Instagram',
        hubDesc1: 'Where the work, vibe and person',
        hubDesc2: 'are checked — the trust hub',
        hubNote: 'First filter on Google / Fresha reviews → final check on Instagram',
        step3Title: '③ Book',
        step3Sub: '“This is the one” is decided',
        entries: ['Google Maps & Search', 'Fresha (booking marketplace)', 'Instagram (discovery)', 'Word of mouth', 'Japanese-community media'],
        bookings: ['Instagram DM', 'Fresha booking link'],
        caption: 'With no single dominant platform like Hot Pepper, Australia’s scattered entry points converge on Instagram, where the booking is decided.',
        aria: 'A diagram of how salons get found in Australia. Scattered entry points — Google Maps, Fresha, Instagram, word of mouth and Japanese-community media — converge on Instagram, the trust hub, leading to a booking via Instagram DM or Fresha.',
      },
      loop: {
        nodes: [
          { label: 'Discovery', sub: 'Instagram · MEO · reviews' },
          { label: 'Consider & book', sub: 'Web · booking flow' },
          { label: 'Repeat', sub: 'SMS · email · Fresha' },
          { label: 'Referrals', sub: 'Reviews · UGC' },
        ],
        centerTitle: 'Treatment',
        centerSub: 'Your domain',
        reflow: 'Reviews flow back to discovery ↻',
        legendOurs: 'What we run',
        legendClient: 'Your domain (care & craft)',
        caption: 'Reviews are the axle: great work → reviews → higher ranking & social proof → new clients.',
        title: 'The growth loop',
        desc: 'A diagram of discovery, consideration and booking, the treatment, repeat visits, and referrals and reviews circling as a loop. Only the central treatment is the owner’s domain; we run everything else. Reviews flow back to discovery to keep the loop turning.',
      },
    },
    home: {
      pricingLabel: 'Pricing',
      pricingHeading: 'Transparent pricing, so you can decide with confidence.',
      pricingLead: 'Every plan is three layers: a one-off setup, an ongoing monthly fee, and optional add-ons.',
      pricingMore: 'See add-ons & full pricing →',
      worksLabel: 'Work',
      worksHeading: 'Selected work',
      worksLead: 'A look at what we’ve built with beauty salons on the Gold Coast.',
      worksMore: 'See all work',
      faqLabel: 'FAQ',
      faqHeading: 'Frequently asked questions',
      faqMore: 'See all questions →',
      serviceMore: 'See service details →',
      aboutMore: 'More about us →',
      logoLabel: (i: number) => `Client / media logo ${i}`,
      heroImageLabel: 'Hero image (salon / lifestyle / Gold Coast)',
      avatarLabel: 'Portrait',
      thumbLabel: (name: string) => `${name} thumbnail`,
      portraitLabel: (role: string) => `${role} portrait`,
    },
    service: {
      heading: 'We run the loop, not just the posts.',
      lead: 'This isn’t one-off social media or a single website build. It’s an external partner running your salon’s entire growth loop, continuously.',
      scopeLabel: 'Scope',
      scopeHeading: 'What we do at each stage of the loop.',
      scopeLead: 'For every stage, the scope and key activities are clear.',
      navLabel: 'Services',
    },
    pricing: {
      heading: 'Pricing is a simple three layers.',
      lead: 'A one-off setup, an ongoing monthly fee, and add-ons only when needed. Build the foundation first, turn the loop each month, add extras as required — clarity above all.',
      optionsLabel: 'Options',
      optionsHeading: 'Add-ons (shared, as needed)',
      optionsLead: 'These can be added to any plan.',
      tableOption: 'Add-on',
      tablePrice: 'Price',
      tableNote: 'Notes',
      faqLabel: 'FAQ',
      faqHeading: 'Pricing questions',
      bandHeading: 'Let’s work out which plan fits.',
      bandSub: 'We’ll listen to where you are and recommend honestly. If Starter is enough, we’ll say so.',
      navLabel: 'Pricing',
    },
    works: {
      heading: 'Selected work',
      lead: 'Real engagements, told as challenge → approach → result.',
      navLabel: 'Work',
      challenge: 'Challenge',
      approach: 'Approach',
      result: 'Result',
      deliverables: 'Deliverables',
      mainVisual: (name: string) => `${name} main visual`,
      detailBandHeading: 'The same system, for your salon.',
    },
    about: {
      heading: 'Japanese quality, delivered through local trust.',
      lead: 'We’re a two-person team spanning Japan and the Gold Coast, Australia.',
      story: [
        'On the Japan side: web production, Instagram management, growth systems and analytics. We bring the marketing and production know-how honed in Japan straight to your salon.',
        'On the Australia side: seven years living on the Gold Coast. Sales, local liaison, coordinating shoots, and above all building trusted relationships and client success.',
        'We’ve seen first-hand how many skilled Japanese salon owners get stuck at the wall of digital marketing — the language, understanding the local market, and the worry of not knowing who to trust.',
        'So we built this as “Japanese execution × local trust.” Not one-off builds or post management, but a growth partner that keeps the whole loop turning, standing beside your salon.',
      ],
      teamHeading: 'Team',
      valuesLabel: 'Values',
      valuesHeading: 'What we care about',
      areasPrefix: 'Areas served: ',
      navLabel: 'About',
    },
    faq: {
      heading: 'Frequently asked questions',
      lead: 'Anything not here? Ask us anything in a free consult.',
      navLabel: 'FAQ',
    },
    contact: {
      heading: 'Let’s talk for 30 minutes — on us.',
      lead: 'Even just a look at where things stand and a few ideas is welcome. We reply within 1–2 business days of your message.',
      bookingHeading: 'Prefer to lock in a time now?',
      bookingBody: 'Book your free consult directly from the calendar.',
      bookingButton: 'Open booking calendar',
      bookingPlaceholder: 'Booking tool to be embedded (Calendly / TimeRex / Spir)',
      otherHeading: 'Other ways to reach us',
      emailPrefix: 'Email: ',
      areasPrefix: 'Areas served: ',
      navLabel: 'Free consult',
    },
    thanks: {
      heading: 'Thank you for getting in touch.',
      body1: 'We’ll review your message and reply by email ',
      bodyStrong: 'within 1–2 business days',
      body2: '.',
      body3: 'If the confirmation email doesn’t arrive, please check your spam folder or contact us directly at ',
      body4: '.',
      back: 'Back to home',
    },
    privacy: {
      title: 'Privacy Policy',
      updated: 'Last updated: 13 June 2026',
    },
  },
} as const;

export type Ui = (typeof ui)[Lang];
